
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MENOS = 4;
  public static final int MENOR = 6;
  public static final int PUNTO = 12;
  public static final int DOSPUNTOS = 11;
  public static final int LETRA = 21;
  public static final int SIGNO = 19;
  public static final int DOBLEPORC = 10;
  public static final int PREG = 16;
  public static final int POR = 14;
  public static final int LLAVECIERRE = 9;
  public static final int COMA = 7;
  public static final int MAYOR = 5;
  public static final int EOF = 0;
  public static final int DIGITO = 20;
  public static final int CONJ = 2;
  public static final int SEP = 17;
  public static final int ESPECIAL = 23;
  public static final int error = 1;
  public static final int DISY = 13;
  public static final int ESPACIO = 18;
  public static final int MAS = 15;
  public static final int PARRAF = 22;
  public static final int LLAVEABRE = 8;
  public static final int PTCOMA = 3;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "CONJ",
  "PTCOMA",
  "MENOS",
  "MAYOR",
  "MENOR",
  "COMA",
  "LLAVEABRE",
  "LLAVECIERRE",
  "DOBLEPORC",
  "DOSPUNTOS",
  "PUNTO",
  "DISY",
  "POR",
  "MAS",
  "PREG",
  "SEP",
  "ESPACIO",
  "SIGNO",
  "DIGITO",
  "LETRA",
  "PARRAF",
  "ESPECIAL"
  };
}

