
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DOSPT = 17;
  public static final int GUION = 10;
  public static final int MENOR = 5;
  public static final int LETRA = 18;
  public static final int SIGNO = 20;
  public static final int POR = 11;
  public static final int PT = 13;
  public static final int COMA = 6;
  public static final int LLAVEDER = 4;
  public static final int EOF = 0;
  public static final int DIGITO = 21;
  public static final int DISYUN = 7;
  public static final int CONJ = 16;
  public static final int SEP = 12;
  public static final int error = 1;
  public static final int ESPECIAL = 14;
  public static final int INTERR = 8;
  public static final int LLAVEIZ = 3;
  public static final int ESPACIO = 19;
  public static final int FIN = 15;
  public static final int MAS = 9;
  public static final int PARRAF = 22;
  public static final int PTCOMA = 2;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PTCOMA",
  "LLAVEIZ",
  "LLAVEDER",
  "MENOR",
  "COMA",
  "DISYUN",
  "INTERR",
  "MAS",
  "GUION",
  "POR",
  "SEP",
  "PT",
  "ESPECIAL",
  "FIN",
  "CONJ",
  "DOSPT",
  "LETRA",
  "ESPACIO",
  "SIGNO",
  "DIGITO",
  "PARRAF"
  };
}

